# Generated by Django 5.2.5 on 2025-10-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeStats',
            fields=[
                ('pincode', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('total_assessments', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('excellent_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('moderate_count', models.IntegerField(default=0)),
                ('concerning_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pincode Statistics',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=6)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField(default=400)),
                ('user_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('ip_address_hash', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pincode', 'timestamp'], name='assessment__pincode_3312a3_idx'), models.Index(fields=['user_fingerprint', 'timestamp'], name='assessment__user_fi_a5c657_idx')],
            },
        ),
    ]
