# Generated by Django 5.2.5 on 2025-10-08 15:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeGeometry',
            fields=[
                ('pincode', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('office_name', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Pincode Boundary',
                'verbose_name_plural': 'Pincode Boundaries',
                'db_table': 'pincode_geometry',
            },
        ),
    ]
