# Generated by Django 5.2.5 on 2025-10-08 19:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_pincodegeometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalBoundaries',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('office_name', models.CharField(blank=True, max_length=200, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('circle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Postal Boundary',
                'verbose_name_plural': 'Postal Boundaries',
                'db_table': 'postal_boundaries',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PincodeGeometry',
        ),
    ]
